version: '3'

services:
  database:
    image: 'postgres:14.2-alpine'
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - dbnet
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
  
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 15433:80
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - dbnet
    volumes:
      - ./pgadmin-data/:/var/lib/pgadmin/

networks: 
  dbnet:
    driver: bridge
